// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7kr_lks0b2Mm3LDDVB73klKWylgMR2o',
    appId: '1:28220411711:web:c6f16484c75da210cccd8a',
    messagingSenderId: '28220411711',
    projectId: 'tabib-7c8ee',
    authDomain: 'tabib-7c8ee.firebaseapp.com',
    storageBucket: 'tabib-7c8ee.firebasestorage.app',
    measurementId: 'G-M9D4CKLDWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE73JKaGGfgPEfzO6W-b5K28S_SsFRN9s',
    appId: '1:28220411711:android:d69ff5f84c21f540cccd8a',
    messagingSenderId: '28220411711',
    projectId: 'tabib-7c8ee',
    storageBucket: 'tabib-7c8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf7s5UASioMPqzc-fhDa-s1uQr8pfWn6U',
    appId: '1:28220411711:ios:26b9f874f1713e89cccd8a',
    messagingSenderId: '28220411711',
    projectId: 'tabib-7c8ee',
    storageBucket: 'tabib-7c8ee.firebasestorage.app',
    iosBundleId: 'com.rishala.tabib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf7s5UASioMPqzc-fhDa-s1uQr8pfWn6U',
    appId: '1:28220411711:ios:26b9f874f1713e89cccd8a',
    messagingSenderId: '28220411711',
    projectId: 'tabib-7c8ee',
    storageBucket: 'tabib-7c8ee.firebasestorage.app',
    iosBundleId: 'com.rishala.tabib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7kr_lks0b2Mm3LDDVB73klKWylgMR2o',
    appId: '1:28220411711:web:8bf8a91133936aa3cccd8a',
    messagingSenderId: '28220411711',
    projectId: 'tabib-7c8ee',
    authDomain: 'tabib-7c8ee.firebaseapp.com',
    storageBucket: 'tabib-7c8ee.firebasestorage.app',
    measurementId: 'G-7WT0XVKHJF',
  );
}
